name: Build Sphinx Documentation

on:
  pull_request:
    branches: [main]

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Sphinx Documentation
        run: |
          cd docs
          # Run Sphinx build to catch issues
          # -D build_toctree=True enables toctree processing to verify all docs are included
          python -m sphinx -b html . _build/html

      - name: Check for broken links to external sites
        run: |
          cd docs
          # Run linkcheck builder to find broken links
          python -m sphinx -b linkcheck . _build/linkcheck
